/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.ics.autobazar.GUI;

import java.util.List;
import sk.upjs.ics.autobazar.InzeratFactory;
import sk.upjs.ics.autobazar.InzeratMotocykel;
import sk.upjs.ics.autobazar.InzeratMotocykelDao;
import sk.upjs.ics.autobazar.InzeratNakladne;
import sk.upjs.ics.autobazar.InzeratNakladneDao;
import sk.upjs.ics.autobazar.InzeratOsobne;
import sk.upjs.ics.autobazar.InzeratOsobneDao;

/**
 *
 * @author PC
 */
public class PouzivatelForm extends javax.swing.JDialog {
    private Long idP = null;

    private InzeratOsobneDao inzeratDao = InzeratFactory.INSTANCE.getInzeratOsobneDao();
    private InzeratNakladneDao inzeratDao2 = InzeratFactory.INSTANCE.getInzeratNakladneDao();
    private InzeratMotocykelDao inzeratDao3 = InzeratFactory.INSTANCE.getInzeratMotocykelDao();

    /**
     * Creates new form PouzivatelForm
     */
    public PouzivatelForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public PouzivatelForm(java.awt.Frame parent, boolean modal, Long idP) {
        super(parent, modal);
        initComponents();
        this.idP=idP;
        refresh();
    }
    
    public void refresh(){
        List<InzeratOsobne> inzeraty = inzeratDao.dajPodlaPouzivatela(idP);
        inzeratyPouzivatelaList.setListData(inzeraty.toArray());
        osobneRadioButton.setSelected(true);
        nadpisLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/upjs/ics/autobazar/ikonky/Transport-Car-icon (1).png")));
    }
    
    public void refresh2(){
        List<InzeratNakladne> inzeraty = inzeratDao2.dajPodlaPouzivatela(idP);
        inzeratyPouzivatelaList.setListData(inzeraty.toArray());
        nadpisLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/upjs/ics/autobazar/ikonky/truck_32.png")));
    }
    
    public void refresh3(){
        List<InzeratMotocykel> inzeraty = inzeratDao3.dajPodlaPouzivatela(idP);
        inzeratyPouzivatelaList.setListData(inzeraty.toArray());
        nadpisLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/upjs/ics/autobazar/ikonky/Transport-Motorcycle-icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        spatButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inzeratyPouzivatelaList = new javax.swing.JList();
        pridatButton = new javax.swing.JButton();
        vymazatButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        osobneRadioButton = new javax.swing.JRadioButton();
        nakladneRadioButton = new javax.swing.JRadioButton();
        motocykleRadioButton = new javax.swing.JRadioButton();
        nadpisLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        spatButton.setText("spat");
        spatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spatButtonActionPerformed(evt);
            }
        });

        inzeratyPouzivatelaList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(inzeratyPouzivatelaList);

        pridatButton.setBackground(new java.awt.Color(102, 255, 102));
        pridatButton.setText("Pridat inzerat");
        pridatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridatButtonActionPerformed(evt);
            }
        });

        vymazatButton.setBackground(new java.awt.Color(255, 0, 0));
        vymazatButton.setText("Vymazat inzerat");
        vymazatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vymazatButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(osobneRadioButton);
        osobneRadioButton.setText("Osobne vozidla");
        osobneRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osobneRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(nakladneRadioButton);
        nakladneRadioButton.setText("Nakladne vozidla");
        nakladneRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nakladneRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(motocykleRadioButton);
        motocykleRadioButton.setText("Motocykle");
        motocykleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motocykleRadioButtonActionPerformed(evt);
            }
        });

        nadpisLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nadpisLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/upjs/ics/autobazar/ikonky/Transport-Car-icon (1).png"))); // NOI18N
        nadpisLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(nadpisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(osobneRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(nakladneRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(motocykleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(pridatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(vymazatButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(spatButton))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(nadpisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(osobneRadioButton)
                .addGap(3, 3, 3)
                .addComponent(nakladneRadioButton)
                .addGap(3, 3, 3)
                .addComponent(motocykleRadioButton)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(pridatButton)
                .addGap(50, 50, 50)
                .addComponent(vymazatButton)
                .addGap(58, 58, 58)
                .addComponent(spatButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spatButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_spatButtonActionPerformed

    private void osobneRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osobneRadioButtonActionPerformed
        refresh();
    }//GEN-LAST:event_osobneRadioButtonActionPerformed

    private void nakladneRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nakladneRadioButtonActionPerformed
        refresh2();
    }//GEN-LAST:event_nakladneRadioButtonActionPerformed

    private void motocykleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motocykleRadioButtonActionPerformed
        refresh3();
    }//GEN-LAST:event_motocykleRadioButtonActionPerformed

    private void vymazatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vymazatButtonActionPerformed
        if (osobneRadioButton.isSelected()) {
            InzeratOsobne inzeratOsobne = (InzeratOsobne) inzeratyPouzivatelaList.getSelectedValue();
            if (inzeratOsobne == null) {
                return;
            }
            inzeratDao.odstranit(inzeratOsobne);
            refresh();
        }
        if (nakladneRadioButton.isSelected()) {
            InzeratNakladne inzeratNakladne = (InzeratNakladne) inzeratyPouzivatelaList.getSelectedValue();
            if (inzeratNakladne == null) {
                return;
            }
            inzeratDao2.odstranit(inzeratNakladne);
            refresh2();
        }
        if (motocykleRadioButton.isSelected()) {
            InzeratMotocykel inzeratMotocykel = (InzeratMotocykel) inzeratyPouzivatelaList.getSelectedValue();
            if (inzeratMotocykel == null) {
                return;
            }
            inzeratDao3.odstranit(inzeratMotocykel);
            refresh3();
        }
    }//GEN-LAST:event_vymazatButtonActionPerformed

    private void pridatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridatButtonActionPerformed
        if (osobneRadioButton.isSelected()) {
            PridatOsobneForm pif = new PridatOsobneForm(null, true, idP);
            pif.setVisible(true);
            refresh();
        }
        if (nakladneRadioButton.isSelected()) {
            PridatNakladneForm pnf = new PridatNakladneForm(null, true, idP);
            pnf.setVisible(true);
            refresh2();
        }
        if (motocykleRadioButton.isSelected()) {
            PridatMotocykelForm pmc = new PridatMotocykelForm(null, true, idP);
            pmc.setVisible(true);
            refresh3();
        }
    }//GEN-LAST:event_pridatButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PouzivatelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PouzivatelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PouzivatelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PouzivatelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PouzivatelForm dialog = new PouzivatelForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JList inzeratyPouzivatelaList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton motocykleRadioButton;
    private javax.swing.JLabel nadpisLabel;
    private javax.swing.JRadioButton nakladneRadioButton;
    private javax.swing.JRadioButton osobneRadioButton;
    private javax.swing.JButton pridatButton;
    private javax.swing.JButton spatButton;
    private javax.swing.JButton vymazatButton;
    // End of variables declaration//GEN-END:variables
}
